(ns kosmos.db-test
  (:require [next.jdbc :as jdbc]
            [next.jdbc.sql :as sql]
            [clojure.test :refer :all]
            [kosmos :refer [map->system start! stop! system]]
            [kosmos.db :refer :all]))

(def config {:hsqldb-server
             {:kosmos/init :kosmos.server/HsqlDbServerComponent
              :port        "9005"
              :database    "file:target/db/test"
              :dbname      "test"}

             :pool {:auto-commit true
                    :maximum-pool-size 2
                    :pool-name "test-pool"}

             :ds
             {:kosmos/init     :kosmos.db/DbComponent
              :kosmos/requires [:hsqldb-server]
              :classname       "org.hsqldb.jdbc.JDBCDriver"
              :dbtype          "hsqldb"
              :dbname          "hsql://localhost:9005/test"
              :user            "SA"
              :password        ""}

             })

(defn setup-db-server [f]
  (start! (map->system config))
  (f)
  (stop!))

(use-fixtures :once setup-db-server)

(defn inserted? [returned]
  (:TEST/ID returned))

;;
;;
(deftest component-with-pooling
  (let [ds (:ds system)]
    (is (= [{:next.jdbc/update-count 0}]
           (jdbc/execute! ds ["drop table test if exists"])))
    (is (= [{:next.jdbc/update-count 0}]
           (jdbc/execute! ds [(str "create table test ("
                                   " id bigint generated by default as identity (start with 1001),"
                                   " name varchar(255) not null,"
                                   " description varchar(255),"
                                   " primary key (id)"
                                   " )")])))

    (is (inserted? (sql/insert! ds :test {:name "test-01" :description "a test record one"})))
    (is (inserted? (sql/insert! ds :test {:name "test-02" :description "a test record two"})))
    (is (inserted? (sql/insert! ds :test {:name "test-03" :description "a test record three"})))
    (is (inserted? (sql/insert! ds :test {:name "test-04" :description "a test record four"})))))
